### PR TITLE
Merge marvel-client to main

### PR DESCRIPTION
**Pull request by jhbforlife**
Completed [Build a Marvel Client](https://fifth-bottom-224.notion.site/Build-a-Marvel-Client-669c3b397f844a96a6e6d4659ca20cb3). Also created cmd folder and moved all existing files there.

Output:
```
3-D Man


A-Bomb (HAS)
Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! 

A.I.M.
AIM is a terrorist organization bent on destroying the world.

Aaron Stack


```

### CODE REVIEW

**Comment by jhbforlife** [comment]
After this class and talking about testing, I have a question. I tried to focus on only exposing the code in the marvel package that I needed to use in main.go to limit observability. With that said, the way this is written is not set up well for testing because I wasn't thinking about testing/ dependency injection. Would the easiest way to get this to be testable and still restrict code access be to make the Client.baseURL exportable to change it when testing?

**Review by jboursiquot — CHANGES_REQUESTED** [review]
This PR contains things unrelated to the marvel assignment.

**Comment by jboursiquot** [comment]
> Would the easiest way to get this to be testable and still restrict code access be to make the Client.baseURL exportable to change it when testing?

You can hide the inner details of the client by creating your own constructor and passing in the bits that are needed (e.g. `marvel.NewClient(privKey, pubKey, url)`)

**Comment by jhbforlife** [comment]
Reverted move to cmd folder for a separate PR. Changed marvel.NewCharClient() to marvel.NewClient(url string) to expose the baseURL to widen its usability and setup for testing. No need to expose the other fields in the Client struct since they should remain the same regardless.

**Review by jboursiquot — APPROVED** [review]
Nice work. Just remove the duplicate README from one of your folders. Good to go.

**Pull request merged**
